name = "Anna Boeva"
role = "VP of Refreshments"
bio = "Hey, I’m Anna! I’m a junior studying Computational Biology with a concentration in Machine Learning and a concentration in Algorithms & Complexity. I’m involved in comp bio research, TAing, and various clubs like CMU Star Wars and Photography. I also enjoy reading, playing video games, and dance!"
coffeeChat = "https://calendly.com/aboeva/30min"
email = "aboeva@andrew.cmu.edu"
image = "/board/anna-boeva.webp"
