name = "Clayton Yu"
role = "VP of External Outreach"
bio = "Hello, I’m Clayton, a sophomore in CB! I’m interested in how complex biological systems can be studied through computation. I’m a TA for 02-120 Programming for Scientists, am involved in InterVarsity Christian Fellowship, and am concert manager for Joyful Noise, an cappella group on campus. I also enjoy binging YouTube and playing video games in my spare time!"
email = "claytony@andrew.cmu.edu"
coffeeChat = "https://calendly.com/claytony-andrew/30min"
image = "/board/clayton-yu.webp"
