name = "Dustin Miao"
role = "VP of Refreshments"
bio = "Hey, I'm Dustin! I am a junior majoring in CS with a concentration in ML and a minor in Bio. Outside of academics, I'm a TA for 15-210 and 10-703, and enjoy playing ping pong and going on long walks  If you're interested in any of the above, please sign up for a coffee chat!"
email = "dustinmi@andrew.cmu.edu"
image = "/board/dustin-miao.webp"
