name = "Emma Li"
role = "Co-President"
bio = "Hi! I’m a junior studying neuroscience and computational biology! I do compbio research and I am the co-president of CBUS and president of the Chinese Dance Club at CMU. Schedule a chat with me if you’re interested in any of these things!"
email = "emmali@andrew.cmu.edu"
coffeeChat = "https://calendar.app.google/ajW2us6Y9cJpid6u9"
image = "/board/emma-li.webp"
priority = 10
