name = "Krit Dass"
role = "VP of Communications"
bio = "Hi, I’m Krit! I’m a sophomore from Orlando studying computer science and computational biology, and I’m especially interested in evolution. I do research in the Pfenning lab, using machine learning to study the evolution of regulatory features across vertebrates. I’m also the lead of the Terrier project in ScottyLabs. In my free time, I enjoy reading, cooking, watching sports (mostly F1 and tennis), and playing badminton and pickleball."
email = "kdass@andrew.cmu.edu"
coffeeChat = "https://calendly.com/kdass-andrew/30min"
image = "/board/krit-dass.webp"
website = "https://kritdass.github.io"
github = "https://github.com/kritdass"
linkedin = "https://linkedin.com/in/kritdass"
