name = "Nihal Josyula"
role = "VP of Internal Outreach"
bio = "Hey, I'm Nihal! I'm a sophomore in Biology and Computational Biology from Seattle. I'm really interested in foundation models for biology, and most recently I interned with an AI group at the NIH NCI, working on deep learning for medical imaging. On campus I'm involved with ScottyLabs and CASI. Outside of that I really like to ski and hike. I also randomly hop on buses into the city since I like exploring."
coffeeChat = "https://calendly.com/nj3004648/30min"
email = "nihaljos@andrew.cmu.edu"
linkedin = "https://www.linkedin.com/in/nihal-josyula/"
github = "https://github.com/nihal-j"
image = "/board/nihal-josyula.webp"
