name = "Tyler Yang"
role = "VP of Internal Outreach"
bio = "Hello, I’m Tyler! I am a junior in SCS. I currently am TAing for 15-210  and I have also done computational chemistry and AI for Science research at CMU via SURA. In my spare time I am part of Futsal Club. Feel free to contact me about anything, and feel free to schedule a coffee chat!"
email = "tylery@andrew.cmu.edu"
linkedin = "https://www.linkedin.com/in/tyler-j-yang/"
github = "https://github.com/88Mangos"
website = "https://88mangos.github.io/"
image = "/board/tyler-yang.webp"
