name = "Viraj Kamath"
role = "VP of Communications"
bio = "Hi, I'm Viraj! I'm a sophomore from Virginia. I'm really interested in computational drug discovery, and most recently I interned with a research group at UPMC working on ovarian cancer suppression. On campus I'm involved with Senate, and in my free time I really like to film videos and read philosophy, as well as watch tv shows (currently watching The Mentalist)."
coffeeChat = "https://calendly.com/virajkam-andrew/coffee-chat"
email = "virajkam@andrew.cmu.edu"
image = "/board/viraj-kamath.webp"
