title = "Fall Welcome Social"
date = 2026-09-10
time = "5:00 PM"
location = "Gates Courtyard"
description = "Casual semester kickoff with food, lawn games, and candy DNA. RSVP for food!"

[[links]]
text = "RSVP"
url = "about:blank"
